mongodb:
  server:   localhost
  database: uptime
  user:     root 
  password:

monitor:
  pollingInterval:        10000    # ten seconds
  updateInterval:         60000    # one minute
  qosAggregationInterval: 3600000  # one hour
  timeout:                5000     # five seconds
  http_proxy:      

server:
  port:     8082
