mongodb:
  server:   localhost
  database: uptime
  user:     root 
  password:

monitor:
  pollingInterval:        10000
  updateInterval:         60000
  qosAggregationInterval: 3600000
  timeout:                5000
  http_proxy:      

server:
  port:     8082
