mongodb:
  server:   localhost
  database: uptime
  user:     root 
  password:

monitor:
  name:                   origin
  apiUrl:                 'http://localhost:8082/api'
  pollingInterval:        10000      # ten seconds
  updateInterval:         60000      # one minute
  qosAggregationInterval: 600000     # ten minutes
  timeout:                5000       # five seconds
  pingHistory:            8035200000 # three months
  proxy:      

autoStartMonitor: true

server:
  port:     8082

verbose: true # only used in dev